version: '3'

services:
  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - "./nginx/volumes/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/volumes/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always

  postgres:
    image: postgres:17.2
    container_name: postgres
    hostname: postgres
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    restart: always
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TZ='Asia/Tokyo'
  
  manage:
    image: manage:1.0.0
    build: ./manage
    container_name: manage
    hostname: manage
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
    restart: always
    logging:
      driver: "json-file" # defaults if not specified
      options:
        max-size: "10m"
        max-file: "10"

  notify:
    image: notify:1.0.0
    build: ./notify
    container_name: notify
    hostname: notify
    restart: always
    logging:
      driver: "json-file" # defaults if not specified
      options:
        max-size: "10m"
        max-file: "10"

